// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerController) DeepCopyInto(out *VerticalPodAutoscalerController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerController.
func (in *VerticalPodAutoscalerController) DeepCopy() *VerticalPodAutoscalerController {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerControllerList) DeepCopyInto(out *VerticalPodAutoscalerControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerticalPodAutoscalerController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerControllerList.
func (in *VerticalPodAutoscalerControllerList) DeepCopy() *VerticalPodAutoscalerControllerList {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSpec) DeepCopyInto(out *VerticalPodAutoscalerSpec) {
	*out = *in
	if in.SafetyMarginFraction != nil {
		in, out := &in.SafetyMarginFraction, &out.SafetyMarginFraction
		*out = new(float64)
		**out = **in
	}
	if in.PodMinCPUMillicores != nil {
		in, out := &in.PodMinCPUMillicores, &out.PodMinCPUMillicores
		*out = new(float64)
		**out = **in
	}
	if in.PodMinMemoryMb != nil {
		in, out := &in.PodMinMemoryMb, &out.PodMinMemoryMb
		*out = new(float64)
		**out = **in
	}
	if in.RecommendationOnly != nil {
		in, out := &in.RecommendationOnly, &out.RecommendationOnly
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSpec.
func (in *VerticalPodAutoscalerSpec) DeepCopy() *VerticalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerStatus) DeepCopyInto(out *VerticalPodAutoscalerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerStatus.
func (in *VerticalPodAutoscalerStatus) DeepCopy() *VerticalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
